In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_raw = pd.read_csv("../data/raw/jps_coastal_erosion_data.csv")

df_raw.head()

,No,Coastal_Cell,District,Area_Location,Longitude_DMS,Latitude_DMS,Longitude_DD,Latitude_DD,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Score,ISMP_2022_Category,NCES_2015_Category
0,1,C1,Besut,North of Kampung Teluk Budu,"102°32'47.8""E","5°50'18.7""N",102.546611,5.838528,4.94,5.00,3.4,17.0,1,1
1,2,C1,Besut,Breakwater near Sungai river mouth,"102°33'26.7""E","5°50'03.3""N",102.557417,5.834250,0.00,0.00,3.2,0.0,3,2
2,3,C1,Besut,Pantai Bukit Keluang,"102°36'17.9""E","5°48'08.2""N",102.604972,5.802278,1.92,2.00,2.3,4.6,3,2
3,11,C2,Setiu,Southeast of Kampung Beting Lintang,"102°39'48.7""E","5°44'08.4""N",102.663528,5.735667,1.79,2.00,2.0,4.0,3,3
4,12,C2,Setiu,Southeast of Kampung Beting Lintang,"102°39'52.4""E","5°44'04.1""N",102.664556,5.734472,2.94,3.00,2.1,6.3,2,3

In [3]:
df_raw.shape

(125, 14)

In [4]:
df_raw.columns.tolist()

['No',
 'Coastal_Cell',
 'District',
 'Area_Location',
 'Longitude_DMS',
 'Latitude_DMS',
 'Longitude_DD',
 'Latitude_DD',
 'Annual_Erosion_Rate_m_yr',
 'Physical_Erosion_Score',
 'Economic_Score',
 'Total_Score',
 'ISMP_2022_Category',
 'NCES_2015_Category']

In [5]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   No                        125 non-null    int64
 1   Coastal_Cell              125 non-null    str
 2   District                  125 non-null    str
 3   Area_Location             125 non-null    str
 4   Longitude_DMS             125 non-null    str
 5   Latitude_DMS              125 non-null    str
 6   Longitude_DD              125 non-null    float64
 7   Latitude_DD               125 non-null    float64
 8   Annual_Erosion_Rate_m_yr  125 non-null    str
 9   Physical_Erosion_Score    125 non-null    str
 10  Economic_Score            125 non-null    float64
 11  Total_Score               125 non-null    float64
 12  ISMP_2022_Category        125 non-null    str
 13  NCES_2015_Category        125 non-null    int64
dtypes: float64(4), int64(2), str(8)
memory usage: 13.8 KB

In [6]:
df_raw.isnull().sum()

No                          0
Coastal_Cell                0
District                    0
Area_Location               0
Longitude_DMS               0
Latitude_DMS                0
Longitude_DD                0
Latitude_DD                 0
Annual_Erosion_Rate_m_yr    0
Physical_Erosion_Score      0
Economic_Score              0
Total_Score                 0
ISMP_2022_Category          0
NCES_2015_Category          0
dtype: int64

In [7]:
df_raw.duplicated().sum()

np.int64(0)

In [8]:
for col in df_raw.columns:
    print(f"\n--- {col} ---")
    print(df_raw[col].unique()[:20])

--- No ---
[ 1  2  3 11 12 13 14 15 16 23 24 25 26 27 28 35 36 37 38 39]

--- Coastal_Cell ---
<StringArray>
['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12']
Length: 12, dtype: str

--- District ---
<StringArray>
['Besut', 'Setiu', 'Kuala Terengganu', 'Marang', 'Dungun', 'Kemaman']
Length: 6, dtype: str

--- Area_Location ---
<StringArray>
[                      'North of Kampung Teluk Budu',
                'Breakwater near Sungai river mouth',
                              'Pantai Bukit Keluang',
               'Southeast of Kampung Beting Lintang',
                   'North of Kampung Bating Lintang',
                       'North of Sungai river mouth',
                         'Sungai Merang river mouth',
 'South of Sungai Mengabang Tapah Besar river mouth',
              'Southeast of Kampung Pengkalan Maras',
                         'North of Kampung Pak Tuyu',
                                  'Kampung Pak Tuyu',
                            'Kampung Seberang Takir',
                'North of Kampung Pantai Batu Buruk',
                      'North of Kampung Gong Pantai',
                               'Kampung Gong Pantai',
                             'East of Kampung Dusun',
                                       'Kampung Aur',
                       'North of Tanjung Chendering',
                                    'Taman Rashidah',
                       'Southeast of Taman Rashidah']
Length: 20, dtype: str

--- Longitude_DMS ---
<StringArray>
['102°32'47.8"E', '102°33'26.7"E', '102°36'17.9"E', '102°39'48.7"E',
 '102°39'52.4"E', '102°39'59.4"E', '102°40'33.4"E', '102°41'27.2"E',
 '102°42'39.6"E', '102°56'40.8"E', '102°56'43.9"E', '102°56'49.4"E',
 '102°56'51.6"E', '102°56'48.8"E', '102°58'56.6"E', '103°04'24.6"E',
 '103°04'50.8"E', '103°05'21.4"E', '103°07'59.0"E', '103°09'21.5"E']
Length: 20, dtype: str

--- Latitude_DMS ---
<StringArray>
['5°50'18.7"N', '5°50'03.3"N', '5°48'08.2"N', '5°44'08.4"N', '5°44'04.1"N',
 '5°43'55.9"N', '5°43'16.1"N', '5°42'18.6"N', '5°41'10.1"N', '5°31'59.9"N',
 '5°31'58.3"N', '5°31'57.4"N', '5°31'52.2"N', '5°31'51.0"N', '5°30'58.4"N',
 '5°25'43.1"N', '5°25'19.0"N', '5°24'49.5"N', '5°21'09.1"N', '5°19'20.2"N']
Length: 20, dtype: str

--- Longitude_DD ---
[102.546611 102.557417 102.604972 102.663528 102.664556 102.6665
 102.675944 102.690889 102.711    102.944667 102.945528 102.947056
 102.947667 102.946889 102.982389 103.0735   103.080778 103.089278
 103.133056 103.155972]

--- Latitude_DD ---
[5.838528 5.83425  5.802278 5.735667 5.734472 5.732194 5.721139 5.705167
 5.686139 5.533306 5.532861 5.532611 5.531167 5.530833 5.516222 5.428639
 5.421944 5.41375  5.352528 5.322278]

--- Annual_Erosion_Rate_m_yr ---
<StringArray>
[     '4.94',      '0.00',      '1.92',      '1.79',      '2.94',      '3.31',
      '2.95',      '2.75',      '4.25',      '0.50',      '0.99',      '0.64',
      '0.51',      '1.01',     '10.18', 'Protected',      '1.44',      '0.74',
      '1.24',      '1.40']
Length: 20, dtype: str

--- Physical_Erosion_Score ---
<StringArray>
[     '5.00',      '0.00',      '2.00',      '3.00',      '4.00',      '0.50',
      '0.99',      '0.64',      '0.51', 'Protected',      '0.74',      '0.95',
      '0.14',      '0.94',      '0.39',      '0.65',      '0.72',      '0.21',
      '0.58',      '0.13']
Length: 20, dtype: str

--- Economic_Score ---
[3.4 3.2 2.3 2.  2.1 1.7 1.2 1.4 1.  3.7 2.6 3.3 2.7 4.  1.5 2.4 2.5 3.5
 1.1 1.9]

--- Total_Score ---
[17.    0.    4.6   4.    6.3   6.8   3.6   4.2   8.5   0.5   0.99  0.64
  0.51  2.   13.    3.    1.78  5.2  13.2   5.  ]

--- ISMP_2022_Category ---
<StringArray>
['1', '3', '2', 'Protected']
Length: 4, dtype: str

--- NCES_2015_Category ---
[1 2 3]

In [9]:
df_raw.dtypes

No                            int64
Coastal_Cell                    str
District                        str
Area_Location                   str
Longitude_DMS                   str
Latitude_DMS                    str
Longitude_DD                float64
Latitude_DD                 float64
Annual_Erosion_Rate_m_yr        str
Physical_Erosion_Score          str
Economic_Score              float64
Total_Score                 float64
ISMP_2022_Category              str
NCES_2015_Category            int64
dtype: object

In [10]:
df_raw["Annual_Erosion_Rate_m_yr"].unique()

<StringArray>
[     '4.94',      '0.00',      '1.92',      '1.79',      '2.94',      '3.31',
      '2.95',      '2.75',      '4.25',      '0.50',      '0.99',      '0.64',
      '0.51',      '1.01',     '10.18', 'Protected',      '1.44',      '0.74',
      '1.24',      '1.40',      '3.56',      '1.62',      '2.27',      '3.00',
      '2.50',      '1.68',      '2.51',      '1.09',      '0.95',      '2.38',
      '0.14',      '0.94',      '1.57',      '0.39',      '1.36',      '1.75',
      '0.65',      '0.72',      '0.21',      '0.58',      '1.49',      '1.30',
      '2.19',      '0.13',      '2.33',      '1.56',      '1.42',      '1.52',
      '0.18',      '1.64',      '0.57',      '1.67',      '2.82',      '0.85',
      '3.36',      '0.82',      '1.35',      '2.80',      '0.84',      '2.08',
      '2.54',      '3.77',      '2.72',      '2.78',      '2.42',      '2.13',
      '1.91',      '0.98',      '2.66',      '1.66',      '1.16',      '2.03',
      '3.30',      '3.40',      '3.91',      '2.63',      '3.74',      '1.00',
      '2.53',      '1.58',      '5.00',      '4.00',      '2.39',      '1.50',
      '2.17',      '8.19',      '1.47',      '0.69',      '0.43',      '0.70',
      '1.25',      '2.97',      '2.11',      '4.02',     '10.56']
Length: 95, dtype: str

In [11]:
df_raw["Physical_Erosion_Score"].unique()

<StringArray>
[     '5.00',      '0.00',      '2.00',      '3.00',      '4.00',      '0.50',
      '0.99',      '0.64',      '0.51', 'Protected',      '0.74',      '0.95',
      '0.14',      '0.94',      '0.39',      '0.65',      '0.72',      '0.21',
      '0.58',      '0.13',      '0.18',      '0.57',      '0.85',      '0.82',
      '0.84',      '0.98',      '0.69',      '0.43',      '0.70']
Length: 29, dtype: str

In [12]:
df_raw["ISMP_2022_Category"].unique()

<StringArray>
['1', '3', '2', 'Protected']
Length: 4, dtype: str

In [13]:
pd.to_numeric(
    df_raw["Annual_Erosion_Rate_m_yr"],
    errors="coerce"
).isna().sum()

np.int64(9)

In [14]:
pd.to_numeric(
    df_raw["Physical_Erosion_Score"],
    errors="coerce"
).isna().sum()

np.int64(9)

In [15]:
df_raw.describe(include="all")

,No,Coastal_Cell,District,Area_Location,Longitude_DMS,Latitude_DMS,Longitude_DD,Latitude_DD,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Score,ISMP_2022_Category,NCES_2015_Category
count,125.000000,125,125,125,125,125,125.000000,125.000000,125,125,125.000000,125.000000,125,125.00000
unique,NaN,12,6,60,125,125,NaN,NaN,95,29,NaN,NaN,4,NaN
top,NaN,C8,Marang,Sungai Mercang river mouth,"102°32'47.8""E","5°50'18.7""N",NaN,NaN,Protected,2.00,NaN,NaN,3,NaN
freq,NaN,46,58,19,1,1,NaN,NaN,9,35,NaN,NaN,85,NaN
mean,80.680000,NaN,NaN,NaN,NaN,NaN,103.249321,5.033971,NaN,NaN,1.831200,3.788480,NaN,2.73600
std,38.460411,NaN,NaN,NaN,NaN,NaN,0.214848,0.368488,NaN,NaN,0.933292,3.857223,NaN,0.58398
min,1.000000,NaN,NaN,NaN,NaN,NaN,102.546611,4.211250,NaN,NaN,1.000000,0.000000,NaN,1.00000
25%,51.000000,NaN,NaN,NaN,NaN,NaN,103.188361,4.731000,NaN,NaN,1.000000,0.840000,NaN,3.00000
50%,82.000000,NaN,NaN,NaN,NaN,NaN,103.282111,5.069444,NaN,NaN,1.400000,3.000000,NaN,3.00000
75%,113.000000,NaN,NaN,NaN,NaN,NaN,103.434028,5.243889,NaN,NaN,2.500000,5.000000,NaN,3.00000
max,144.000000,NaN,NaN,NaN,NaN,NaN,103.484222,5.838528,NaN,NaN,4.000000,17.000000,NaN,3.00000

In [16]:
erosion_numeric = pd.to_numeric(
    df_raw["Annual_Erosion_Rate_m_yr"],
    errors="coerce"
)

df_raw[erosion_numeric.isna()][
    [
        "No",
        "Coastal_Cell",
        "District",
        "Area_Location",
        "Annual_Erosion_Rate_m_yr",
        "Physical_Erosion_Score",
        "Economic_Score",
        "Total_Score",
        "ISMP_2022_Category"
    ]
]

,No,Coastal_Cell,District,Area_Location,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Score,ISMP_2022_Category
16,36,C4,Setiu,North of Kampung Pak Tuyu,Protected,Protected,3.3,0.0,Protected
17,37,C4,Setiu,Kampung Pak Tuyu,Protected,Protected,2.7,0.0,Protected
18,38,C5,Kuala Terengganu,Kampung Seberang Takir,Protected,Protected,4.0,0.0,Protected
90,110,C9,Dungun,Kampung Sura,Protected,Protected,2.1,0.0,Protected
91,111,C9,Dungun,Kampung Sura,Protected,Protected,2.5,0.0,Protected
92,112,C9,Dungun,Kampung Balai Besar,Protected,Protected,2.5,0.0,Protected
100,120,C10,Dungun,Sand spit near Sungai Paka river mouth,Protected,Protected,1.1,0.0,Protected
118,138,C11,Kemaman,Pantai Kemasik (north),Protected,Protected,2.8,0.0,Protected
119,139,C11,Kemaman,Kampung Tengah,Protected,Protected,2.8,0.0,Protected

In [17]:
df_raw[
    df_raw["Annual_Erosion_Rate_m_yr"].astype(str).str.contains(
        "Protected",
        case=False,
        na=False
    )
]

,No,Coastal_Cell,District,Area_Location,Longitude_DMS,Latitude_DMS,Longitude_DD,Latitude_DD,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Score,ISMP_2022_Category,NCES_2015_Category
16,36,C4,Setiu,North of Kampung Pak Tuyu,"103°04'50.8""E","5°25'19.0""N",103.080778,5.421944,Protected,Protected,3.3,0.0,Protected,2
17,37,C4,Setiu,Kampung Pak Tuyu,"103°05'21.4""E","5°24'49.5""N",103.089278,5.413750,Protected,Protected,2.7,0.0,Protected,1
18,38,C5,Kuala Terengganu,Kampung Seberang Takir,"103°07'59.0""E","5°21'09.1""N",103.133056,5.352528,Protected,Protected,4.0,0.0,Protected,1
90,110,C9,Dungun,Kampung Sura,"103°25'26.3""E","4°45'18.5""N",103.423972,4.755139,Protected,Protected,2.1,0.0,Protected,3
91,111,C9,Dungun,Kampung Sura,"103°25'31.1""E","4°45'00.7""N",103.425306,4.750194,Protected,Protected,2.5,0.0,Protected,2
92,112,C9,Dungun,Kampung Balai Besar,"103°25'34.2""E","4°44'51.7""N",103.426167,4.747694,Protected,Protected,2.5,0.0,Protected,2
100,120,C10,Dungun,Sand spit near Sungai Paka river mouth,"103°26'22.8""E","4°38'50.8""N",103.439667,4.647444,Protected,Protected,1.1,0.0,Protected,1
118,138,C11,Kemaman,Pantai Kemasik (north),"103°27'18.7""E","4°25'33.9""N",103.455194,4.426083,Protected,Protected,2.8,0.0,Protected,1
119,139,C11,Kemaman,Kampung Tengah,"103°27'20.3""E","4°25'25.2""N",103.455639,4.423667,Protected,Protected,2.8,0.0,Protected,1

In [18]:
physical_numeric = pd.to_numeric(
    df_raw["Physical_Erosion_Score"],
    errors="coerce"
)

economic_numeric = pd.to_numeric(
    df_raw["Economic_Score"],
    errors="coerce"
)

calculated_total = physical_numeric * economic_numeric

score_check = df_raw[
    physical_numeric.notna()
    & (
        abs(calculated_total - df_raw["Total_Score"]) > 0.01
    )
][
    [
        "No",
        "Coastal_Cell",
        "Area_Location",
        "Physical_Erosion_Score",
        "Economic_Score",
        "Total_Score"
    ]
]

score_check

,No,Coastal_Cell,Area_Location,Physical_Erosion_Score,Economic_Score,Total_Score
108,128,C10,Petronas Kertih Refinery,5.00,3.1,9.3

In [19]:
expected_numbers = set(
    range(
        int(df_raw["No"].min()),
        int(df_raw["No"].max()) + 1
    )
)

actual_numbers = set(df_raw["No"])

missing_station_numbers = sorted(
    expected_numbers - actual_numbers
)

print("Missing station numbers:")
print(missing_station_numbers)

print("Number of missing station numbers:",
      len(missing_station_numbers))

Missing station numbers:
[4, 5, 6, 7, 8, 9, 10, 17, 18, 19, 20, 21, 22, 29, 30, 31, 32, 33, 34]
Number of missing station numbers: 19

In [20]:
print(
    "Latitude range:",
    df_raw["Latitude_DD"].min(),
    "to",
    df_raw["Latitude_DD"].max()
)

print(
    "Longitude range:",
    df_raw["Longitude_DD"].min(),
    "to",
    df_raw["Longitude_DD"].max()
)

Latitude range: 4.21125 to 5.838528
Longitude range: 102.546611 to 103.484222