In [1]:
import pandas as pd
import numpy as np

from pyproj import Geod
from scipy.interpolate import PchipInterpolator

ModuleNotFoundError: No module named 'pyproj'

In [2]:
import pandas as pd
import numpy as np

from pyproj import Geod
from scipy.interpolate import PchipInterpolator

In [3]:
df = pd.read_csv(
    "../data/cleaned/jps_coastal_erosion_cleaned.csv"
)

df.head()

,No,Coastal_Cell,District,Area_Location,Longitude_DMS,Latitude_DMS,Longitude_DD,Latitude_DD,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Score,ISMP_2022_Category,NCES_2015_Category,Is_Protected,Original_Total_Score,Total_Score_Cleaned,Is_Erosion_Outlier,ISMP_2022_Category_Numeric
0,1,C1,Besut,North of Kampung Teluk Budu,"102°32'47.8""E","5°50'18.7""N",102.546611,5.838528,4.94,5.0,3.4,17.0,1,1,0,17.0,17.0,0,1.0
1,2,C1,Besut,Breakwater near Sungai river mouth,"102°33'26.7""E","5°50'03.3""N",102.557417,5.834250,0.00,0.0,3.2,0.0,3,2,0,0.0,0.0,0,3.0
2,3,C1,Besut,Pantai Bukit Keluang,"102°36'17.9""E","5°48'08.2""N",102.604972,5.802278,1.92,2.0,2.3,4.6,3,2,0,4.6,4.6,0,3.0
3,11,C2,Setiu,Southeast of Kampung Beting Lintang,"102°39'48.7""E","5°44'08.4""N",102.663528,5.735667,1.79,2.0,2.0,4.0,3,3,0,4.0,4.0,0,3.0
4,12,C2,Setiu,Southeast of Kampung Beting Lintang,"102°39'52.4""E","5°44'04.1""N",102.664556,5.734472,2.94,3.0,2.1,6.3,2,3,0,6.3,6.3,0,2.0

In [4]:
print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nProtected locations:")
print(df["Is_Protected"].value_counts())

print("\nMissing values:")
print(df.isnull().sum())

Dataset shape: (125, 19)

Columns:
['No', 'Coastal_Cell', 'District', 'Area_Location', 'Longitude_DMS', 'Latitude_DMS', 'Longitude_DD', 'Latitude_DD', 'Annual_Erosion_Rate_m_yr', 'Physical_Erosion_Score', 'Economic_Score', 'Total_Score', 'ISMP_2022_Category', 'NCES_2015_Category', 'Is_Protected', 'Original_Total_Score', 'Total_Score_Cleaned', 'Is_Erosion_Outlier', 'ISMP_2022_Category_Numeric']

Protected locations:
Is_Protected
0    116
1      9
Name: count, dtype: int64

Missing values:
No                            0
Coastal_Cell                  0
District                      0
Area_Location                 0
Longitude_DMS                 0
Latitude_DMS                  0
Longitude_DD                  0
Latitude_DD                   0
Annual_Erosion_Rate_m_yr      9
Physical_Erosion_Score        9
Economic_Score                0
Total_Score                   0
ISMP_2022_Category            0
NCES_2015_Category            0
Is_Protected                  0
Original_Total_Score          0
Total_Score_Cleaned           9
Is_Erosion_Outlier            0
ISMP_2022_Category_Numeric    9
dtype: int64

In [5]:
import pandas as pd
import numpy as np

from pyproj import Geod
from scipy.interpolate import PchipInterpolator

In [6]:
df = pd.read_csv(
    "../data/cleaned/jps_coastal_erosion_cleaned.csv"
)

df.head()

,No,Coastal_Cell,District,Area_Location,Longitude_DMS,Latitude_DMS,Longitude_DD,Latitude_DD,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Score,ISMP_2022_Category,NCES_2015_Category,Is_Protected,Original_Total_Score,Total_Score_Cleaned
0,1,C1,Besut,North of Kampung Teluk Budu,"102°32'47.8""E","5°50'18.7""N",102.546611,5.838528,4.94,5.0,3.4,17.0,1,1,0,17.0,17.0
1,2,C1,Besut,Breakwater near Sungai river mouth,"102°33'26.7""E","5°50'03.3""N",102.557417,5.834250,0.00,0.0,3.2,0.0,3,2,0,0.0,0.0
2,3,C1,Besut,Pantai Bukit Keluang,"102°36'17.9""E","5°48'08.2""N",102.604972,5.802278,1.92,2.0,2.3,4.6,3,2,0,4.6,4.6
3,11,C2,Setiu,Southeast of Kampung Beting Lintang,"102°39'48.7""E","5°44'08.4""N",102.663528,5.735667,1.79,2.0,2.0,4.0,3,3,0,4.0,4.0
4,12,C2,Setiu,Southeast of Kampung Beting Lintang,"102°39'52.4""E","5°44'04.1""N",102.664556,5.734472,2.94,3.0,2.1,6.3,2,3,0,6.3,6.3

In [7]:
print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nProtected locations:")
print(df["Is_Protected"].value_counts())

print("\nMissing values:")
print(df.isnull().sum())

Dataset shape: (125, 17)

Columns:
['No', 'Coastal_Cell', 'District', 'Area_Location', 'Longitude_DMS', 'Latitude_DMS', 'Longitude_DD', 'Latitude_DD', 'Annual_Erosion_Rate_m_yr', 'Physical_Erosion_Score', 'Economic_Score', 'Total_Score', 'ISMP_2022_Category', 'NCES_2015_Category', 'Is_Protected', 'Original_Total_Score', 'Total_Score_Cleaned']

Protected locations:
Is_Protected
0    116
1      9
Name: count, dtype: int64

Missing values:
No                          0
Coastal_Cell                0
District                    0
Area_Location               0
Longitude_DMS               0
Latitude_DMS                0
Longitude_DD                0
Latitude_DD                 0
Annual_Erosion_Rate_m_yr    9
Physical_Erosion_Score      9
Economic_Score              0
Total_Score                 0
ISMP_2022_Category          0
NCES_2015_Category          0
Is_Protected                0
Original_Total_Score        0
Total_Score_Cleaned         0
dtype: int64

In [8]:
df = (
    df.sort_values("No")
    .reset_index(drop=True)
)

In [9]:
print("First JPS No:", df["No"].min())
print("Last JPS No:", df["No"].max())
print("Number of source locations:", len(df))

First JPS No: 1
Last JPS No: 144
Number of source locations: 125

In [10]:
geod = Geod(ellps="WGS84")

segment_distances = []

for i in range(len(df) - 1):
    lon1 = df.loc[i, "Longitude_DD"]
    lat1 = df.loc[i, "Latitude_DD"]

    lon2 = df.loc[i + 1, "Longitude_DD"]
    lat2 = df.loc[i + 1, "Latitude_DD"]

    _, _, distance_m = geod.inv(
        lon1,
        lat1,
        lon2,
        lat2
    )

    segment_distances.append(distance_m)

df.loc[:-2, "Distance_to_Next_m"] = segment_distances

ValueError: Must have equal len keys and value when setting with an iterable

In [11]:
geod = Geod(ellps="WGS84")

segment_distances = []

for i in range(len(df) - 1):
    lon1 = df.loc[i, "Longitude_DD"]
    lat1 = df.loc[i, "Latitude_DD"]

    lon2 = df.loc[i + 1, "Longitude_DD"]
    lat2 = df.loc[i + 1, "Latitude_DD"]

    _, _, distance_m = geod.inv(
        lon1,
        lat1,
        lon2,
        lat2
    )

    segment_distances.append(distance_m)

# Add NaN for the final station because it has no next station
df["Distance_to_Next_m"] = segment_distances + [np.nan]

print("Number of segments:", len(segment_distances))

Number of segments: 124

In [12]:
print(
    "Approximate connected coastline distance:",
    round(sum(segment_distances) / 1000, 2),
    "km"
)

Approximate connected coastline distance: 227.39 km

In [13]:
df["Cumulative_Distance_m"] = 0.0

for i in range(1, len(df)):
    df.loc[i, "Cumulative_Distance_m"] = (
        df.loc[i - 1, "Cumulative_Distance_m"]
        + segment_distances[i - 1]
    )

df[
    [
        "No",
        "Coastal_Cell",
        "Cumulative_Distance_m"
    ]
].head()

   No Coastal_Cell  Cumulative_Distance_m
0   1           C1               0.000000
1   2           C1            1286.840821
2   3           C1            7630.262995
3  11           C2           17444.764585
4  12           C2           17619.204510

In [14]:
print(
    "Final cumulative distance:",
    round(df["Cumulative_Distance_m"].iloc[-1] / 1000, 2),
    "km"
)

Final cumulative distance: 227.39 km

In [15]:
spacing_m = 20

total_distance = df["Cumulative_Distance_m"].iloc[-1]

target_distances = np.arange(
    0,
    total_distance + spacing_m,
    spacing_m
)

target_distances = target_distances[
    target_distances <= total_distance
]

print("Spacing:", spacing_m, "m")
print("Generated target points:", len(target_distances))

Spacing: 20 m
Generated target points: 11370

In [16]:
generated_rows = []

segment_index = 0

for transect_id, target_distance in enumerate(
    target_distances,
    start=1
):

    while (
        segment_index < len(df) - 2
        and target_distance >
        df.loc[segment_index + 1, "Cumulative_Distance_m"]
    ):
        segment_index += 1

    start_row = df.loc[segment_index]
    end_row = df.loc[segment_index + 1]

    segment_start = start_row["Cumulative_Distance_m"]
    segment_end = end_row["Cumulative_Distance_m"]

    segment_length = segment_end - segment_start

    if segment_length == 0:
        fraction = 0
    else:
        fraction = (
            target_distance - segment_start
        ) / segment_length

    lon1 = start_row["Longitude_DD"]
    lat1 = start_row["Latitude_DD"]

    lon2 = end_row["Longitude_DD"]
    lat2 = end_row["Latitude_DD"]

    azimuth, _, distance = geod.inv(
        lon1,
        lat1,
        lon2,
        lat2
    )

    longitude, latitude, _ = geod.fwd(
        lon1,
        lat1,
        azimuth,
        distance * fraction
    )

    generated_rows.append({
        "Transect_ID": f"T{transect_id:05d}",
        "Distance_Along_Coast_m": target_distance,
        "Latitude_DD": latitude,
        "Longitude_DD": longitude,
        "Source_Start_No": start_row["No"],
        "Source_End_No": end_row["No"]
    })

transects = pd.DataFrame(generated_rows)

transects.head()

,Transect_ID,Distance_Along_Coast_m,Latitude_DD,Longitude_DD,Source_Start_No,Source_End_No
0,T00001,0.0,5.838528,102.546611,1,2
1,T00002,20.0,5.838462,102.546779,1,2
2,T00003,40.0,5.838395,102.546947,1,2
3,T00004,60.0,5.838329,102.547115,1,2
4,T00005,80.0,5.838262,102.547283,1,2

In [17]:
print("Generated rows:", len(transects))
print("Generated columns:", len(transects.columns))

transects.tail()

Generated rows: 11370
Generated columns: 6

,Transect_ID,Distance_Along_Coast_m,Latitude_DD,Longitude_DD,Source_Start_No,Source_End_No
11365,T11366,227300.0,4.212024,103.439844,143,144
11366,T11367,227320.0,4.211856,103.439776,143,144
11367,T11368,227340.0,4.211689,103.439707,143,144
11368,T11369,227360.0,4.211522,103.439639,143,144
11369,T11370,227380.0,4.211354,103.439571,143,144

In [18]:
source_distances = df["Cumulative_Distance_m"].to_numpy()

nearest_indices = []

for target_distance in transects["Distance_Along_Coast_m"]:
    nearest_index = np.abs(
        source_distances - target_distance
    ).argmin()

    nearest_indices.append(nearest_index)

transects["Nearest_Source_Index"] = nearest_indices

In [19]:
transects["Nearest_JPS_No"] = [
    df.loc[i, "No"] for i in nearest_indices
]

transects["Coastal_Cell"] = [
    df.loc[i, "Coastal_Cell"] for i in nearest_indices
]

transects["District"] = [
    df.loc[i, "District"] for i in nearest_indices
]

transects["Nearest_JPS_Location"] = [
    df.loc[i, "Area_Location"] for i in nearest_indices
]

transects["NCES_2015_Category"] = [
    df.loc[i, "NCES_2015_Category"] for i in nearest_indices
]

transects["Is_Protected"] = [
    df.loc[i, "Is_Protected"] for i in nearest_indices
]

In [20]:
transects.head()

,Transect_ID,Distance_Along_Coast_m,Latitude_DD,Longitude_DD,Source_Start_No,Source_End_No,Nearest_Source_Index,Nearest_JPS_No,Coastal_Cell,District,Nearest_JPS_Location,NCES_2015_Category,Is_Protected
0,T00001,0.0,5.838528,102.546611,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0
1,T00002,20.0,5.838462,102.546779,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0
2,T00003,40.0,5.838395,102.546947,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0
3,T00004,60.0,5.838329,102.547115,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0
4,T00005,80.0,5.838262,102.547283,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0

In [21]:
transects["Is_Protected"].value_counts()

Is_Protected
0    10296
1     1074
Name: count, dtype: int64

In [22]:
def interpolate_valid_feature(
    source_df,
    target_distances,
    column
):
    valid = source_df[column].notna()

    x = source_df.loc[
        valid,
        "Cumulative_Distance_m"
    ].to_numpy()

    y = source_df.loc[
        valid,
        column
    ].to_numpy()

    interpolator = PchipInterpolator(
        x,
        y,
        extrapolate=True
    )

    return interpolator(target_distances)

In [23]:
transects["Annual_Erosion_Rate_m_yr"] = (
    interpolate_valid_feature(
        df,
        transects["Distance_Along_Coast_m"],
        "Annual_Erosion_Rate_m_yr"
    )
)

transects["Physical_Erosion_Score"] = (
    interpolate_valid_feature(
        df,
        transects["Distance_Along_Coast_m"],
        "Physical_Erosion_Score"
    )
)

transects["Economic_Score"] = (
    interpolate_valid_feature(
        df,
        transects["Distance_Along_Coast_m"],
        "Economic_Score"
    )
)

In [24]:
transects["Physical_Erosion_Score"] = (
    transects["Physical_Erosion_Score"]
    .clip(0, 5)
)

transects["Economic_Score"] = (
    transects["Economic_Score"]
    .clip(1, 4)
)

In [25]:
protected_mask = (
    transects["Is_Protected"] == 1
)

transects.loc[
    protected_mask,
    "Annual_Erosion_Rate_m_yr"
] = np.nan

transects.loc[
    protected_mask,
    "Physical_Erosion_Score"
] = np.nan

In [26]:
transects["Total_Risk_Score"] = (
    transects["Physical_Erosion_Score"]
    * transects["Economic_Score"]
)

In [27]:
transects.loc[
    protected_mask,
    "Total_Risk_Score"
] = 0.0

In [28]:
print("Total generated points:", len(transects))

print(
    "Protected generated points:",
    transects["Is_Protected"].sum()
)

print("\nMissing values:")
print(
    transects[
        [
            "Annual_Erosion_Rate_m_yr",
            "Physical_Erosion_Score",
            "Economic_Score",
            "Total_Risk_Score"
        ]
    ].isnull().sum()
)

Total generated points: 11370
Protected generated points: 1074

Missing values:
Annual_Erosion_Rate_m_yr    1074
Physical_Erosion_Score      1074
Economic_Score                 0
Total_Risk_Score               0
dtype: int64

In [29]:
transects[
    transects["Is_Protected"] == 1
][
    [
        "Transect_ID",
        "Coastal_Cell",
        "Nearest_JPS_Location",
        "Annual_Erosion_Rate_m_yr",
        "Physical_Erosion_Score",
        "Economic_Score",
        "Total_Risk_Score",
        "Is_Protected"
    ]
].head(10)

,Transect_ID,Coastal_Cell,Nearest_JPS_Location,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Risk_Score,Is_Protected
3765,T03766,C4,North of Kampung Pak Tuyu,NaN,NaN,2.951657,0.0,1
3766,T03767,C4,North of Kampung Pak Tuyu,NaN,NaN,2.970827,0.0,1
3767,T03768,C4,North of Kampung Pak Tuyu,NaN,NaN,2.989941,0.0,1
3768,T03769,C4,North of Kampung Pak Tuyu,NaN,NaN,3.008948,0.0,1
3769,T03770,C4,North of Kampung Pak Tuyu,NaN,NaN,3.027797,0.0,1
3770,T03771,C4,North of Kampung Pak Tuyu,NaN,NaN,3.046437,0.0,1
3771,T03772,C4,North of Kampung Pak Tuyu,NaN,NaN,3.064817,0.0,1
3772,T03773,C4,North of Kampung Pak Tuyu,NaN,NaN,3.082885,0.0,1
3773,T03774,C4,North of Kampung Pak Tuyu,NaN,NaN,3.100590,0.0,1
3774,T03775,C4,North of Kampung Pak Tuyu,NaN,NaN,3.117881,0.0,1

In [30]:
non_protected = transects[
    transects["Is_Protected"] == 0
]

print("Erosion rate:")
print(
    non_protected["Annual_Erosion_Rate_m_yr"]
    .describe()
)

print("\nPhysical erosion score:")
print(
    non_protected["Physical_Erosion_Score"]
    .describe()
)

print("\nEconomic score:")
print(
    non_protected["Economic_Score"]
    .describe()
)

Erosion rate:
count    10296.000000
mean         2.371010
std          1.902651
min          0.000000
25%          0.891402
50%          2.112563
75%          3.344570
max         10.530535
Name: Annual_Erosion_Rate_m_yr, dtype: float64

Physical erosion score:
count    10296.000000
mean         2.405607
std          1.470711
min          0.000000
25%          1.045539
50%          2.274563
75%          3.813266
max          5.000000
Name: Physical_Erosion_Score, dtype: float64

Economic score:
count    10296.000000
mean         1.777621
std          0.807765
min          1.000000
25%          1.006223
50%          1.526706
75%          2.291049
max          4.000000
Name: Economic_Score, dtype: float64

In [31]:
negative_erosion = non_protected[
    non_protected["Annual_Erosion_Rate_m_yr"] < 0
]

print(
    "Negative erosion values:",
    len(negative_erosion)
)

Negative erosion values: 0

In [32]:
valid_erosion = df[
    df["Annual_Erosion_Rate_m_yr"].notna()
]

reconstructed_erosion = interpolate_valid_feature(
    df,
    valid_erosion["Cumulative_Distance_m"],
    "Annual_Erosion_Rate_m_yr"
)

erosion_error = np.abs(
    reconstructed_erosion
    - valid_erosion["Annual_Erosion_Rate_m_yr"].to_numpy()
)

print(
    "Maximum interpolation error at JPS source points:",
    erosion_error.max()
)

Maximum interpolation error at JPS source points: 0.0

In [33]:
cell_counts = (
    transects["Coastal_Cell"]
    .value_counts()
    .sort_index()
)

cell_counts

Coastal_Cell
C1      627
C10    1100
C11     990
C12     617
C2     1399
C3      906
C4     1134
C5      314
C6      483
C7      308
C8     2720
C9      772
Name: count, dtype: int64

In [34]:
print(
    "Protected percentage:",
    round(
        transects["Is_Protected"].mean() * 100,
        2
    ),
    "%"
)

Protected percentage: 9.45 %

In [35]:
print("Final dataset shape:", transects.shape)
print("Duplicate Transect IDs:", transects["Transect_ID"].duplicated().sum())

print(
    "Duplicate coordinates:",
    transects.duplicated(
        subset=["Latitude_DD", "Longitude_DD"]
    ).sum()
)

print("Protected derived points:", transects["Is_Protected"].sum())

print("\nMissing values:")
print(transects.isnull().sum())

Final dataset shape: (11370, 17)
Duplicate Transect IDs: 0
Duplicate coordinates: 0
Protected derived points: 1074

Missing values:
Transect_ID                    0
Distance_Along_Coast_m         0
Latitude_DD                    0
Longitude_DD                   0
Source_Start_No                0
Source_End_No                  0
Nearest_Source_Index           0
Nearest_JPS_No                 0
Coastal_Cell                   0
District                       0
Nearest_JPS_Location           0
NCES_2015_Category             0
Is_Protected                   0
Annual_Erosion_Rate_m_yr    1074
Physical_Erosion_Score      1074
Economic_Score                 0
Total_Risk_Score               0
dtype: int64

In [36]:
import os

os.makedirs("../data/processed", exist_ok=True)

transects.to_csv(
    "../data/processed/terengganu_coastal_erosion_transects.csv",
    index=False
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.

In [37]:
df_check = pd.read_csv(
    "../data/processed/terengganu_coastal_erosion_transects.csv"
)

print("Saved dataset shape:", df_check.shape)
df_check.head()

Saved dataset shape: (11370, 17)

,Transect_ID,Distance_Along_Coast_m,Latitude_DD,Longitude_DD,Source_Start_No,Source_End_No,Nearest_Source_Index,Nearest_JPS_No,Coastal_Cell,District,Nearest_JPS_Location,NCES_2015_Category,Is_Protected,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Risk_Score
0,T00001,0.0,5.838528,102.546611,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0,4.940000,5.000000,3.400000,17.000000
1,T00002,20.0,5.838462,102.546779,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0,4.848510,4.907369,3.396846,16.669576
2,T00003,40.0,5.838395,102.546947,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0,4.755592,4.813296,3.393691,16.334837
3,T00004,60.0,5.838329,102.547115,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0,4.661339,4.717872,3.390535,15.996112
4,T00005,80.0,5.838262,102.547283,1,2,0,1,C1,Besut,North of Kampung Teluk Budu,1,0,4.565840,4.621190,3.387380,15.653724

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/cleaned/jps_coastal_erosion_cleaned_144.csv"
)

print("Dataset shape:", df.shape)
print("Total JPS stations:", len(df))
print("Protected stations:", df["Is_Protected"].sum())

df.head()

Dataset shape: (144, 18)
Total JPS stations: 144
Protected stations: 9

,No,Coastal_Cell,District,Area_Location,Longitude_DMS,Latitude_DMS,Longitude_DD,Latitude_DD,Annual_Erosion_Rate_m_yr,Physical_Erosion_Score,Economic_Score,Total_Score,ISMP_2022_Category,NCES_2015_Category,Is_Protected,Original_Total_Score,Total_Score_Cleaned,Is_Erosion_Outlier
0,1,C1,Besut,North of Kampung Teluk Budu,"102°32'47.8""E","5°50'18.7""N",102.546611,5.838528,4.94,5.00,3.4,17.00,1,1,0,17.00,17.00,False
1,2,C1,Besut,Breakwater near Sungai Besut river mouth,"102°33'26.7""E","5°50'03.3""N",102.557417,5.834250,0.00,0.00,3.2,0.00,3,2,0,0.00,0.00,False
2,3,C1,Besut,Pantai Bukit Keluang,"102°36'17.9""E","5°48'08.2""N",102.604972,5.802278,1.92,2.00,2.3,4.60,3,2,0,4.60,4.60,False
3,4,C1,Besut,Pantai Bukit Keluang,"102°36'35.9""E","5°47'56.6""N",102.609972,5.799056,0.94,0.94,1.4,1.32,3,3,0,1.32,1.32,False
4,5,C1,Besut,Pantai Bukit Keluang,"102°36'40.1""E","5°47'51.6""N",102.611139,5.797667,5.28,5.00,1.0,5.00,3,3,0,5.00,5.00,False

In [2]:
from pyproj import Geod

# Sort stations by JPS number
df_sorted = df.sort_values("No").reset_index(drop=True)

# Extract coordinates
lons = df_sorted["Longitude_DD"].to_numpy()
lats = df_sorted["Latitude_DD"].to_numpy()

# Calculate distances between consecutive stations
geod = Geod(ellps="WGS84")

_, _, distances = geod.inv(
    lons[:-1], lats[:-1],
    lons[1:], lats[1:]
)

# Convert metres to kilometres
df_sorted["Gap_From_Previous_km"] = np.r_[
    np.nan, distances / 1000
]

print("Total JPS stations:", len(df_sorted))

print("Missing coordinates:")
print(df_sorted[
    ["Latitude_DD", "Longitude_DD"]
].isnull().sum())

print("\nTotal straight-line distance (km):",
      round(distances.sum() / 1000, 2))

print("\n8 largest gaps between stations:")
print(
    df_sorted.nlargest(
        8, "Gap_From_Previous_km"
    )[
        ["No", "Coastal_Cell",
         "Area_Location", "Gap_From_Previous_km"]
    ].round(2)
)

Total JPS stations: 144
Missing coordinates:
Latitude_DD     0
Longitude_DD    0
dtype: int64

Total straight-line distance (km): 225.27

8 largest gaps between stations:
      No Coastal_Cell                      Area_Location  Gap_From_Previous_km
21    22           C3  West of Sungai Merang river mouth                 25.29
107  108           C8               Kampung Teluk Bedara                 11.42
140  141          C11                       Kampung Ibai                  9.49
28    29           C4        North of Kampung Batu Rakit                  9.17
37    38           C5             Kampung Seberang Takir                  8.33
106  107           C8     Sungai Kuala Abang river mouth                  7.33
9     10           C2            North of Kampung Beting                  7.02
133  134          C11   Kelab Golf and Rekreasi Petronas                  6.80

In [3]:
# Identify large gaps between JPS stations

df_sorted["Previous_No"] = (
    df_sorted["No"].shift(1).astype("Int64")
)

print("Gaps larger than 3 km:",
      (df_sorted["Gap_From_Previous_km"] > 3).sum())

print("Gaps larger than 5 km:",
      (df_sorted["Gap_From_Previous_km"] > 5).sum())

print("Gaps larger than 10 km:",
      (df_sorted["Gap_From_Previous_km"] > 10).sum())

print("\nStations with gaps larger than 3 km:")

print(
    df_sorted.loc[
        df_sorted["Gap_From_Previous_km"] > 3,
        ["Previous_No", "No",
         "Coastal_Cell", "Gap_From_Previous_km"]
    ].round(2).to_string(index=False)
)

Gaps larger than 3 km: 23
Gaps larger than 5 km: 13
Gaps larger than 10 km: 2

Stations with gaps larger than 3 km:
 Previous_No  No Coastal_Cell  Gap_From_Previous_km
           2   3           C1                  6.34
           9  10           C2                  7.02
          15  16           C2                  3.06
          21  22           C3                 25.29
          27  28           C4                  4.25
          28  29           C4                  9.17
          37  38           C5                  8.33
          38  39           C6                  4.20
          66  67           C8                  6.00
          68  69           C8                  3.01
          81  82           C8                  3.61
          82  83           C8                  4.28
          93  94           C8                  4.86
         106 107           C8                  7.33
         107 108           C8                 11.42
         118 119           C9                  3.07
         119 120          C10                  5.79
         131 132          C10                  4.01
         133 134          C11                  6.80
         140 141          C11                  9.49
         141 142          C12                  5.97
         142 143          C12                  5.72
         143 144          C12                  3.64

In [4]:
# Maximum allowed gap between stations
MAX_GAP_KM = 3.0

# Identify where a new coastal segment begins
df_sorted["Start_New_Segment"] = (
    df_sorted["Gap_From_Previous_km"].isna()
    | (df_sorted["Gap_From_Previous_km"] > MAX_GAP_KM)
    | (
        df_sorted["Coastal_Cell"]
        != df_sorted["Coastal_Cell"].shift(1)
    )
)

# Assign segment IDs
df_sorted["Segment_ID"] = (
    df_sorted["Start_New_Segment"].cumsum()
)

# Summarize segments
segment_summary = df_sorted.groupby("Segment_ID").agg(
    Coastal_Cell=("Coastal_Cell", "first"),
    Start_No=("No", "first"),
    End_No=("No", "last"),
    Station_Count=("No", "size")
)

print("Total segments:", len(segment_summary))
print("Total stations retained:", segment_summary["Station_Count"].sum())

print("Single-station segments:",
      (segment_summary["Station_Count"] == 1).sum())

print("\nSegment Summary:")
print(segment_summary.to_string())

Total segments: 27
Total stations retained: 144
Single-station segments: 10

Segment Summary:
           Coastal_Cell  Start_No  End_No  Station_Count
Segment_ID
1                    C1         1       2              2
2                    C1         3       9              7
3                    C2        10      15              6
4                    C2        16      21              6
5                    C3        22      27              6
6                    C4        28      28              1
7                    C4        29      37              9
8                    C5        38      38              1
9                    C6        39      47              9
10                   C7        48      62             15
11                   C8        63      66              4
12                   C8        67      68              2
13                   C8        69      81             13
14                   C8        82      82              1
15                   C8        83      93             11
16                   C8        94     106             13
17                   C8       107     107              1
18                   C8       108     108              1
19                   C9       109     118             10
20                   C9       119     119              1
21                  C10       120     131             12
22                  C10       132     133              2
23                  C11       134     140              7
24                  C11       141     141              1
25                  C12       142     142              1
26                  C12       143     143              1
27                  C12       144     144              1

In [5]:
SPACING_M = 20

# Select consecutive stations within the same segment
# Both stations must be non-protected
eligible_pairs = df_sorted[
    (
        df_sorted["Segment_ID"] ==
        df_sorted["Segment_ID"].shift(1)
    )
    &
    (df_sorted["Is_Protected"] == 0)
    &
    (df_sorted["Is_Protected"].shift(1) == 0)
].copy()

# Estimate how many 20-metre points will be generated
eligible_pairs["Estimated_New_Points"] = (
    np.ceil(
        eligible_pairs["Gap_From_Previous_km"] * 1000
        / SPACING_M
    ).astype(int) - 1
).clip(lower=0)

print("Eligible station pairs:", len(eligible_pairs))

print("Interpolation distance (km):",
      round(eligible_pairs["Gap_From_Previous_km"].sum(), 2))

print("Estimated new points:",
      eligible_pairs["Estimated_New_Points"].sum())

print("Original JPS stations:", len(df_sorted))

print("Estimated total points:",
      len(df_sorted) +
      eligible_pairs["Estimated_New_Points"].sum())

Eligible station pairs: 107
Interpolation distance (km): 53.64
Estimated new points: 2631
Original JPS stations: 144
Estimated total points: 2775

In [6]:
generated_points = []

for end_idx in eligible_pairs.index:
    start = df_sorted.iloc[end_idx - 1]
    end = df_sorted.iloc[end_idx]

    azimuth, _, distance_m = geod.inv(
        start["Longitude_DD"],
        start["Latitude_DD"],
        end["Longitude_DD"],
        end["Latitude_DD"]
    )

    for d in np.arange(SPACING_M, distance_m, SPACING_M):
        lon, lat, _ = geod.fwd(
            start["Longitude_DD"],
            start["Latitude_DD"],
            azimuth,
            float(d)
        )

        generated_points.append({
            "Start_JPS_No": int(start["No"]),
            "End_JPS_No": int(end["No"]),
            "Segment_ID": int(start["Segment_ID"]),
            "Latitude_DD": lat,
            "Longitude_DD": lon,
            "Distance_From_Start_m": d,
            "Fraction_Between_Stations": d / distance_m
        })

df_generated = pd.DataFrame(generated_points)

print("Generated new points:", len(df_generated))
print("Original JPS stations:", len(df_sorted))
print("Total points:", len(df_generated) + len(df_sorted))

df_generated.head()

Generated new points: 2631
Original JPS stations: 144
Total points: 2775

,Start_JPS_No,End_JPS_No,Segment_ID,Latitude_DD,Longitude_DD,Distance_From_Start_m,Fraction_Between_Stations
0,1,2,1,5.838462,102.546779,20.0,0.015542
1,1,2,1,5.838395,102.546947,40.0,0.031084
2,1,2,1,5.838329,102.547115,60.0,0.046626
3,1,2,1,5.838262,102.547283,80.0,0.062168
4,1,2,1,5.838196,102.547451,100.0,0.077710

In [7]:
# Step 7: Interpolate erosion data for generated points

source = df_sorted.set_index("No")

fraction = df_generated["Fraction_Between_Stations"]

features = [
    "Annual_Erosion_Rate_m_yr",
    "Physical_Erosion_Score",
    "Economic_Score"
]

# Interpolate numerical values
for col in features:

    start_values = df_generated["Start_JPS_No"].map(source[col])
    end_values = df_generated["End_JPS_No"].map(source[col])

    df_generated[col] = (
        start_values +
        (end_values - start_values) * fraction
    ).round(4)

# Calculate estimated total risk score
df_generated["Total_Score_Cleaned"] = (
    df_generated["Physical_Erosion_Score"] *
    df_generated["Economic_Score"]
).round(2)

# Generated points come from non-protected station pairs
df_generated["Is_Protected"] = 0

# Assign coastal cell
df_generated["Coastal_Cell"] = (
    df_generated["Start_JPS_No"].map(source["Coastal_Cell"])
)

# Keep track of nearest original JPS station
df_generated["Nearest_JPS_No"] = np.where(
    fraction <= 0.5,
    df_generated["Start_JPS_No"],
    df_generated["End_JPS_No"]
)

df_generated["District"] = (
    df_generated["Nearest_JPS_No"].map(source["District"])
)

df_generated["Area_Location"] = (
    df_generated["Nearest_JPS_No"].map(source["Area_Location"])
)

df_generated["Source_Type"] = "Interpolated"

print("Generated points:", len(df_generated))

print("\nMissing feature values:")
print(df_generated[features].isnull().sum())

print("\nFirst 5 generated points:")
print(df_generated[
    [
        "Latitude_DD",
        "Longitude_DD",
        "Annual_Erosion_Rate_m_yr",
        "Physical_Erosion_Score",
        "Economic_Score",
        "Total_Score_Cleaned"
    ]
].head())

Generated points: 2631

Missing feature values:
Annual_Erosion_Rate_m_yr    0
Physical_Erosion_Score      0
Economic_Score              0
dtype: int64

First 5 generated points:
   Latitude_DD  Longitude_DD  Annual_Erosion_Rate_m_yr  \
0     5.838462    102.546779                    4.8632
1     5.838395    102.546947                    4.7864
2     5.838329    102.547115                    4.7097
3     5.838262    102.547283                    4.6329
4     5.838196    102.547451                    4.5561

   Physical_Erosion_Score  Economic_Score  Total_Score_Cleaned
0                  4.9223          3.3969                16.72
1                  4.8446          3.3938                16.44
2                  4.7669          3.3907                16.16
3                  4.6892          3.3876                15.89
4                  4.6115          3.3845                15.61

In [8]:
# Step 8: Combine original and generated coastal points

# Copy original JPS stations
df_original = df_sorted.copy()

# Identify original records
df_original["Source_Type"] = "JPS_Original"

df_original["Start_JPS_No"] = df_original["No"]
df_original["End_JPS_No"] = df_original["No"]
df_original["Nearest_JPS_No"] = df_original["No"]

df_original["Distance_From_Start_m"] = 0.0
df_original["Fraction_Between_Stations"] = 0.0

# Combine both datasets
df_combined = pd.concat(
    [df_original, df_generated],
    ignore_index=True
)

# Sort by coastal segment and station
df_combined = df_combined.sort_values(
    ["Segment_ID", "Start_JPS_No",
     "Fraction_Between_Stations"]
).reset_index(drop=True)

# Assign unique IDs
df_combined["Transect_ID"] = np.arange(
    1, len(df_combined) + 1
)

print("=== COMBINED DATASET ===")
print("Total points:", len(df_combined))

print("\nSource distribution:")
print(df_combined["Source_Type"].value_counts())

print("\nProtected points:",
      df_combined["Is_Protected"].sum())

print("\nMissing erosion rates:",
      df_combined["Annual_Erosion_Rate_m_yr"].isnull().sum())

print("\nFirst 5 rows:")
print(df_combined[
    ["Transect_ID", "Start_JPS_No", "Segment_ID",
     "Source_Type", "Annual_Erosion_Rate_m_yr"]
].head())

=== COMBINED DATASET ===
Total points: 2775

Source distribution:
Source_Type
Interpolated    2631
JPS_Original     144
Name: count, dtype: int64

Protected points: 9

Missing erosion rates: 9

First 5 rows:
   Transect_ID  Start_JPS_No  Segment_ID   Source_Type  \
0            1             1           1  JPS_Original
1            2             1           1  Interpolated
2            3             1           1  Interpolated
3            4             1           1  Interpolated
4            5             1           1  Interpolated

   Annual_Erosion_Rate_m_yr
0                    4.9400
1                    4.8632
2                    4.7864
3                    4.7097
4                    4.6329

In [9]:
# Step 9: Final dataset verification

features = [
    "Annual_Erosion_Rate_m_yr",
    "Physical_Erosion_Score",
    "Economic_Score"
]

print("=== FINAL TRANSECT VERIFICATION ===")

print("Total points:", len(df_combined))

print("Duplicate Transect IDs:",
      df_combined["Transect_ID"].duplicated().sum())

print("\nMissing coordinates:")
print(df_combined[
    ["Latitude_DD", "Longitude_DD"]
].isnull().sum())

print("\nMissing features in non-protected points:")
print(
    df_combined.loc[
        df_combined["Is_Protected"] == 0,
        features
    ].isnull().sum()
)

print("\nSource distribution:")
print(df_combined["Source_Type"].value_counts())

print("\nProtected points:",
      df_combined["Is_Protected"].sum())

print("\nTotal is correct:",
      len(df_combined) == 2775)

=== FINAL TRANSECT VERIFICATION ===
Total points: 2775
Duplicate Transect IDs: 0

Missing coordinates:
Latitude_DD     0
Longitude_DD    0
dtype: int64

Missing features in non-protected points:
Annual_Erosion_Rate_m_yr    0
Physical_Erosion_Score      0
Economic_Score              0
dtype: int64

Source distribution:
Source_Type
Interpolated    2631
JPS_Original     144
Name: count, dtype: int64

Protected points: 9

Total is correct: True

In [10]:
import os
import pandas as pd

# Create processed folder if needed
os.makedirs("../data/processed", exist_ok=True)

# Save new dataset without overwriting the old one
output_path = "../data/processed/terengganu_coastal_erosion_transects_144.csv"

df_combined.to_csv(output_path, index=False)

# Reload to verify
df_check = pd.read_csv(output_path)

print("Dataset saved successfully!")
print("Total points:", len(df_check))
print("Total columns:", len(df_check.columns))

print("\nSource distribution:")
print(df_check["Source_Type"].value_counts())

print("\nProtected points:")
print(df_check["Is_Protected"].sum())

print("\nFile location:", output_path)

Dataset saved successfully!
Total points: 2775
Total columns: 29

Source distribution:
Source_Type
Interpolated    2631
JPS_Original     144
Name: count, dtype: int64

Protected points:
9

File location: ../data/processed/terengganu_coastal_erosion_transects_144.csv